server.port: 8095

db.url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"

request.payload.logging.maxlength: 2000

stubrunner.stubs:
  repository.root: "http://dl.bintray.com/4finance/micro"
  group: com.ofg
  module: stub-runner-examples

stubrunner.use-microservice-definitions: true
stubrunner.skip-local-repo: true